name: Terraform Infrastructure

on:
  workflow_call:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create backend bucket if missing
        run: |
          aws s3api head-bucket --bucket lara-aws-tf-prod 2>/dev/null || \
          aws s3 mb s3://lara-aws-tf-prod --region us-east-1

      - name: Terraform Init
        run: terraform init

      - name: Validate Terraform
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Check Terraform variable
        env:
          TF_VAR_app_key: ${{ secrets.APP_KEY }}
        run: |
          if [ -z "$TF_VAR_app_key" ]; then
            echo "APP_KEY is NOT available"
            exit 1
          fi

          echo "APP_KEY is available"
          echo "APP_KEY length: ${#TF_VAR_app_key}"

      - name: Terraform Apply
        env:
          TF_VAR_app_key: ${{ secrets.APP_KEY }}
        run: terraform apply --auto-approve